# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(843, 649)
        self.table = QtWidgets.QTableWidget(Form)
        self.table.setGeometry(QtCore.QRect(30, 40, 771, 351))
        self.table.setMouseTracking(False)
        self.table.setTabletTracking(False)
        self.table.setAutoFillBackground(False)
        self.table.setObjectName("table")
        self.table.setColumnCount(7)
        self.table.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.table.verticalHeaderItem(0)
        item.setText(_translate("Form", "0"))
        item = self.table.verticalHeaderItem(1)
        item.setText(_translate("Form", "1"))
        item = self.table.verticalHeaderItem(2)
        item.setText(_translate("Form", "2"))
        item = self.table.verticalHeaderItem(3)
        item.setText(_translate("Form", "3"))
        item = self.table.verticalHeaderItem(4)
        item.setText(_translate("Form", "4"))
        item = self.table.verticalHeaderItem(5)
        item.setText(_translate("Form", "5"))
        item = self.table.verticalHeaderItem(6)
        item.setText(_translate("Form", "6"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "0"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "1"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "2"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "3"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "4"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "5"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "6"))
